services:
  - type: web
    name: todo-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres:[Supabase@1234]@db.fmckorjmiebjzjulaguq.supabase.co:5432/postgres"
